package pe.edu.upeu.bibliomobil.theme

import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

private val Claro = lightColorScheme(
    primaryFixed = Color(0xFFCEE5FF),
    primaryFixedDim = Color(0xFF9ACBFA),
    onPrimaryFixed = Color(0xFF073451),
    onPrimaryFixedVariant = Color(0xFF245A81),
    secondaryFixed = Color(0xFFDDE3EC),
    secondaryFixedDim = Color(0xFFC1C7D0),
    onSecondaryFixed = Color(0xFF161D25),
    onSecondaryFixedVariant = Color(0xFF414851),
    tertiaryFixed = Color(0xFFFFDEAA),
    tertiaryFixedDim = Color(0xFFF5BC62),
    onTertiaryFixed = Color(0xFF432C00),
    onTertiaryFixedVariant = Color(0xFF634300),
    primary = Color(0xFF245A81),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFCEE5FF),
    onPrimaryContainer = Color(0xFF073451),
    inversePrimary = Color(0xFF9ACBFA),
    secondary = Color(0xFF59616A),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDDE3EC),
    onSecondaryContainer = Color(0xFF161D25),
    tertiary = Color(0xFF825500),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDEAA),
    onTertiaryContainer = Color(0xFF432C00),
    background = Color(0xFFFCF9F3),
    onBackground = Color(0xFF1B1C1E),
    surface = Color(0xFFFCF9F3),
    onSurface = Color(0xFF1B1C1E),
    surfaceVariant = Color(0xFFDFE3E8),
    onSurfaceVariant = Color(0xFF42474D),
    surfaceTint = Color(0xFF245A81),
    inverseSurface = Color(0xFF303134),
    inverseOnSurface = Color(0xFFF3F0EB),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF72777D),
    outlineVariant = Color(0xFFC2C7CD),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFCF9F3),
    surfaceDim = Color(0xFFDCD9D4),
    surfaceContainer = Color(0xFFF0EDE7),
    surfaceContainerHigh = Color(0xFFEAE7E1),
    surfaceContainerHighest = Color(0xFFE4E1DB),
    surfaceContainerLow = Color(0xFFF6F3ED),
    surfaceContainerLowest = Color(0xFFFFFFFF)
)

private val Oscuro = darkColorScheme(
    primaryFixed = Color(0xFFCEE5FF),
    primaryFixedDim = Color(0xFF9ACBFA),
    onPrimaryFixed = Color(0xFF073451),
    onPrimaryFixedVariant = Color(0xFF245A81),
    secondaryFixed = Color(0xFFDDE3EC),
    secondaryFixedDim = Color(0xFFC1C7D0),
    onSecondaryFixed = Color(0xFF161D25),
    onSecondaryFixedVariant = Color(0xFF414851),
    tertiaryFixed = Color(0xFFFFDEAA),
    tertiaryFixedDim = Color(0xFFF5BC62),
    onTertiaryFixed = Color(0xFF432C00),
    onTertiaryFixedVariant = Color(0xFF634300),
    primary = Color(0xFF9ACBFA),
    onPrimary = Color(0xFF003352),
    primaryContainer = Color(0xFF073451),
    onPrimaryContainer = Color(0xFFCEE5FF),
    inversePrimary = Color(0xFF245A81),
    secondary = Color(0xFFC1C7D0),
    onSecondary = Color(0xFF2B323A),
    secondaryContainer = Color(0xFF414851),
    onSecondaryContainer = Color(0xFFDDE3EC),
    tertiary = Color(0xFFF5BC62),
    onTertiary = Color(0xFF452E00),
    tertiaryContainer = Color(0xFF634300),
    onTertiaryContainer = Color(0xFFFFDEAA),
    background = Color(0xFF121416),
    onBackground = Color(0xFFE3E2E6),
    surface = Color(0xFF121416),
    onSurface = Color(0xFFE3E2E6),
    surfaceVariant = Color(0xFF42474D),
    onSurfaceVariant = Color(0xFFC2C7CD),
    surfaceTint = Color(0xFF9ACBFA),
    inverseSurface = Color(0xFFE3E2E6),
    inverseOnSurface = Color(0xFF303134),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF8C9197),
    outlineVariant = Color(0xFF42474D),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF383A3D),
    surfaceDim = Color(0xFF121416),
    surfaceContainer = Color(0xFF1E2023),
    surfaceContainerHigh = Color(0xFF282A2D),
    surfaceContainerHighest = Color(0xFF333538),
    surfaceContainerLow = Color(0xFF1A1C1F),
    surfaceContainerLowest = Color(0xFF0D0F11)
)

@Composable
fun BiblioMobilTheme(oscuro: Boolean, content: @Composable () -> Unit) {
    MaterialTheme(colorScheme = if (oscuro) Oscuro else Claro, content = content)
}
